### ISSUE TITLE
파이어폭스 안됨

### ISSUE THREAD

**Issue by meandy124** [toriato/koolside#10]
~오류에 대한 짧은 설명을 작성해주세요, 어디에서 무엇이 작동하지 않는다 형태로 써주시면 됩니다~

** 오류 메세지 (옵션) **
```
1. 브라우저에서 F12 를 눌러 개발자 모드를 엽니다.
2. Console 또는 콘솔이라 적혀있는 탭을 엽니다.
3. 시뻘건 오류 메세지를 ``` 사이에 복붙합니다.
```

** 기기 정보 **
 - 브라우저: ~예시: 크롬 80.0~
 - 확장 기능: ~예시: Tampermonkey~

파폭 안된다 violentmonkey씀

**Comment by toriato** [comment]
새 버전 확인해주세요

**Comment by toriato** [comment]
여전히 안되면 이슈 다시 열어주세요

**Comment by meandy124** [comment]
안됨 이젠 아예 게시글도 다 안보임 고쳐봐 좀 ㅠㅠ

**Comment by toriato** [comment]
업데이트 해봄?

**Comment by toriato** [comment]
https://github.com/toriato/koolside/blob/2229fccd625d733241383a8df8cb60cb2a31eccd/src/index.ts#L11
확인해보니까 이 부분에서 다음으로 안넘어가서 초기화가 안되는 오류 있었음
수정판 올렸음

**Comment by toriato** [comment]
안되면 언제든지 다시 열어주셈
