### ISSUE TITLE
글 제목이 제대로 나오지 않음

### ISSUE THREAD

**Issue by Datusilla** [toriato/koolside#17]
글 제목이 강제로 여러번 줄바꿈 됨. 드레그 외에 글 체크 기능 없음. 목록에 표시되는 글 수 적음
[https://imgur.com/878ESM0](url)
누르면 깃헙 내부에서 찾기 때문에 없다고 뜸. 주소창 복붙으로 보셈

## 기기 정보
 - 브라우저: 크롬 최신판
 - 확장 기능: 바이올런트 몽키

**Comment by toriato** [comment]
완장 권한 있을 때 체크박스 정상적으로 추가 안되는 버그 같음 확인해보겠음

**Comment by toriato** [comment]
v0.2.2 수정
