### ISSUE TITLE
검색이 안됨

### ISSUE THREAD

**Issue by Datusilla** [toriato/koolside#18]
검색어를 넣으면 원래 나오는 검색어 관련된 게시물 목록이 아니라 검색을 안했을 때의 최근 게시물들만 뜸.

2, 3 으로 페이지를 넘겨도 검색을 안했을 때의 다음, 다다음 페이지 최근 게시물 목록이 뜸.

## 기기 정보
 - 브라우저: 크롬 최신판
 - 확장 기능: 바이올런트 몽키

**Comment by toriato** [comment]
v0.2.4 수정
